---

# Common to all services
x-common: &common
    restart: "no"

x-password: &password "password"

networks:
    default:

volumes:
    activemq-data: {}
    blazegraph-data: {}
    cantaloupe-data: {}
    code-server-data: {}
    drupal-private-files: {}
    drupal-public-files: {}
    drupal-root: {}
    drupal-solr-config: {}
    fcrepo-data: {}
    mariadb-data: {}
    matomo-data: {}
    solr-data: {}

services:
    alpaca:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/alpaca:${ISLANDORA_TAG}
        environment:
          ALPACA_ACTIVEMQ_CONNECTIONS: 20
          ALPACA_ACTIVEMQ_CONSUMERS: 8
    crayfits:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/crayfits:${ISLANDORA_TAG}
    fits:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/fits:${ISLANDORA_TAG}
    homarus:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/homarus:${ISLANDORA_TAG}
    houdini:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/houdini:${ISLANDORA_TAG}
    hypercube:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/hypercube:${ISLANDORA_TAG}
    mariadb:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/mariadb:${ISLANDORA_TAG}
        volumes:
            - mariadb-data:/var/lib/mysql:rw
    milliner:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/milliner:${ISLANDORA_TAG}
    activemq:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/activemq:${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.routers.activemq_http.entrypoints: http
            traefik.http.routers.activemq_http.rule: Host(`activemq.islandora.io`)
            traefik.http.routers.activemq_http.service: activemq
            traefik.http.services.activemq.loadbalancer.server.port: 8161
        environment:
          ACTIVEMQ_WEB_ADMIN_PASSWORD: *password
        volumes:
            - activemq-data:/opt/activemq/data:rw
    blazegraph:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/blazegraph:${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.routers.blazegraph_http.entrypoints: http
            traefik.http.routers.blazegraph_http.rule: Host(`blazegraph.islandora.io`)
            traefik.http.routers.blazegraph_http.service: blazegraph
            traefik.http.services.blazegraph.loadbalancer.server.port: 8080
        volumes:
            - blazegraph-data:/data:rw
    cantaloupe:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/cantaloupe:${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.middlewares.cantaloupe-custom-request-headers.headers.customrequestheaders.X-Forwarded-Path: /cantaloupe
            traefik.http.middlewares.cantaloupe-strip-prefix.stripprefix.prefixes: /cantaloupe
            traefik.http.middlewares.cantaloupe.chain.middlewares: cantaloupe-strip-prefix,cantaloupe-custom-request-headers
            traefik.http.routers.cantaloupe_http.entrypoints: http
            traefik.http.routers.cantaloupe_http.middlewares: cantaloupe
            traefik.http.routers.cantaloupe_http.rule: Host(`islandora.io`) && PathPrefix(`/cantaloupe`)
            traefik.http.routers.cantaloupe_http.service: cantaloupe
            traefik.http.services.cantaloupe.loadbalancer.server.port: 8182
        volumes:
            - cantaloupe-data:/data:rw
    drupal:
        <<: *common
        image: ${REPOSITORY}/sandbox:${TAG}
        build:
          context: drupal
          args:
              REPOSITORY: ${ISLANDORA_REPOSITORY}
              TAG: ${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.routers.drupal_http.entrypoints: http
            traefik.http.routers.drupal_http.rule: Host(`islandora.io`)
            traefik.http.routers.drupal_http.service: drupal
            traefik.http.services.drupal.loadbalancer.server.port: 80
        environment:
            DRUPAL_ACTIVEMQ_WEB_ADMIN_PASSWORD: *password
            DRUPAL_DEFAULT_ACCOUNT_PASSWORD: *password
            DRUPAL_DEFAULT_BROKER_URL: "tcp://activemq:61613"
            DRUPAL_DEFAULT_CANTALOUPE_URL: "http://islandora.io/cantaloupe/iiif/2"
            DRUPAL_DEFAULT_CONFIGDIR: "/var/www/drupal/config/sync"
            DRUPAL_DEFAULT_FCREPO_HOST: "fcrepo"
            DRUPAL_DEFAULT_FCREPO_PORT: 8080
            DRUPAL_DEFAULT_FCREPO_URL: "http://fcrepo.islandora.io/fcrepo/rest/"
            DRUPAL_DEFAULT_INSTALL_EXISTING_CONFIG: "true"
            DRUPAL_DEFAULT_MATOMO_URL: "http://islandora.io/matomo/"
            DRUPAL_DEFAULT_NAME: "Islandora Sandbox"
            DRUPAL_DEFAULT_PROFILE: "minimal"
            DRUPAL_DEFAULT_SITE_ALIAS_SANDBOX: "sandbox.islandora.io"
            DRUPAL_DEFAULT_SITE_URL: "islandora.io"
            DRUPAL_DEFAULT_SOLR_CORE: "default"
            DRUPAL_DRUSH_URI: "http://islandora.io" # Used by docker/drupal/rootfs/usr/local/share/custom/install.sh
            NGINX_FASTCGI_CONNECT_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_FASTCGI_READ_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_FASTCGI_SEND_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_KEEPALIVE_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_PROXY_CONNECT_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_PROXY_READ_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_PROXY_SEND_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            NGINX_SEND_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}s
            PHP_DEFAULT_SOCKET_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}
            PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
            PHP_MAX_INPUT_TIME: ${PHP_MAX_EXECUTION_TIME}
            PHP_PROCESS_CONTROL_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}
            PHP_REQUEST_TERMINATE_TIMEOUT: ${PHP_MAX_EXECUTION_TIME}
        volumes:
            - type: volume
              source: drupal-public-files
              target: /var/www/drupal/web/sites/default/files
            - type: volume
              source: drupal-private-files
              target: /var/www/drupal/private
            - drupal-solr-config:/opt/solr/server/solr/default:ro
    fcrepo:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/fcrepo6:${ISLANDORA_TAG}
        environment:
            FCREPO_ALLOW_EXTERNAL_DEFAULT: "http://default/"
            FCREPO_ALLOW_EXTERNAL_DRUPAL: "http://islandora.io/"
        labels:
            traefik.enable: true
            traefik.http.routers.fcrepo_http.entrypoints: http
            traefik.http.routers.fcrepo_http.rule: Host(`fcrepo.islandora.io`)
            traefik.http.routers.fcrepo_http.service: fcrepo
            traefik.http.services.fcrepo.loadbalancer.server.port: 8080
        volumes:
            - fcrepo-data:/data:rw
    solr:
        <<: *common
        image: ${ISLANDORA_REPOSITORY}/solr:${ISLANDORA_TAG}
        labels:
            traefik.enable: true
            traefik.http.routers.solr_http.entrypoints: http
            traefik.http.routers.solr_http.rule: Host(`solr.islandora.io`)
            traefik.http.routers.solr_http.service: solr
            traefik.http.services.solr.loadbalancer.server.port: 8983
        volumes:
            - solr-data:/data:rw
            - type: volume
              source: drupal-solr-config
              target: /opt/solr/server/solr/default
              volume:
                  nocopy: true
    traefik:
        <<: *common
        image: traefik:v2.8.3
        command: >-
            --api.insecure=true
            --api.dashboard=true
            --api.debug=true
            --entryPoints.http.address=:80
            --providers.docker=true
            --providers.docker.network=default
            --providers.docker.exposedByDefault=false
            '--providers.docker.defaultRule=Host(`{{index .Labels "com.docker.compose.service" }}.islandora.io`)'
        labels:
            traefik.enable: true
            traefik.http.routers.traefik_http.entrypoints: http
            traefik.http.routers.traefik_http.service: traefik
            traefik.http.services.traefik.loadbalancer.server.port: 8080
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
            default:
                aliases:
                    # Allow services to connect on the same name/port as the outside.
                    - blazegraph.islandora.io
                    - fcrepo.islandora.io
                    - islandora.io
                    - solr.islandora.io
        depends_on:
            # Sometimes traefik doesn't pick up on new containers so make sure they are started before traefik.
            - activemq
            - blazegraph
            - drupal
            - fcrepo
            - solr

